networks:
  webnet:
    driver: bridge

services:
  caddy:
    container_name: caddy-webserver
    image: caddy:alpine
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - "${CADDYFILE}:/etc/caddy/Caddyfile"
      - "${SITE_DIR}:/usr/share/caddy"
      - "${DATA_DIR}:/data"
      - "${CONFIG_DIR}:/config"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - webnet

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    networks:
      - webnet

    env_file:
      - .env
