services:
  caddy:
    image: caddy:alpine
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80/tcp
    volumes:
      - ./src:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./logs:/var/log/caddy:rw
    restart: unless-stopped
